version: '2'
services:
  demo:
    #build:
      #context: ./
      #dockerfile: ./Dockerfile
    restart: always
    container_name: demo
    #与xml中配置保持一致！！
    image: sochinlar/demo:0.3
    ports:
      - 8081:8081
    networks:
      mysql:
        aliases:
          - demo
      webservice:
        aliases:
          - demo

  nginx:
    restart: always
    container_name: nginx
    #command: docker run --name nginx -p 80:80 --privileged=true -d nginx
    privileged: true
    volumes:
      - /opt/dockerdata/nginx/html:/usr/share/nginx/html
      - /opt/dockerdata/nginx/log:/var/log/nginx
      - /opt/dockerdata/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/dockerdata/nginx/conf.d:/etc/nginx/conf.d
    image: nginx
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:5.7
    container_name: mysql2
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "81:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PORT=3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=123456

networks:
  mysql:
  webservice: